// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewManagementService.Data;

namespace ReviewManagementService.Migrations
{
    [DbContext(typeof(ReviewContext))]
    [Migration("20200427062324_ReviewServicemig1")]
    partial class ReviewServicemig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReviewManagementService.Model.Rating", b =>
                {
                    b.Property<int>("rateid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ratedate");

                    b.Property<decimal>("rating");

                    b.Property<int>("restaurentid");

                    b.Property<string>("review");

                    b.Property<int>("userid");

                    b.HasKey("rateid");

                    b.ToTable("Rating");
                });
#pragma warning restore 612, 618
        }
    }
}
